PPW_Exercise_Neo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('lab_11.urls', 'lab_11'), namespace='lab_11')),
    # path('', include(('lab_6.urls', 'lab_6'), namespace='lab_6')),
    # path('registration/', include('lab_10.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
]

lab_10/urls.py
from django.urls import path
from lab_10.views import index, new, email_checking, subscriber_list, subscriber_data

urlpatterns = [
    path('', index, name = 'registration'),
    path('new/', new, name = 'new'),
    path('email_checking/', email_checking, name = 'email_checking'),
    path('subscriber_list/', subscriber_list, name = 'subscriber_list'),
    path('subscriber_data/', subscriber_data, name = 'subscriber_data'),
    # path('password_confirmation/', password_confirmation, name = 'password_confirmation'),
]

lab_11/urls.py
from django.urls import path
from lab_11.views import index, google_book, favorite, logout

urlpatterns = [
    path('', index, name = 'book'),
    path('book/', index, name = 'book'),
    path('google_book/<str:url>/', google_book, name='google_book'),
    path('favorite/', favorite, name='favorite'),
    path('logout/', logout, name='logout'),
]

lab_6/urls.py
from django.urls import path
from lab_6.views import index, add_status, about, book_list, book_data

urlpatterns = [
    path('', index, name = 'home'),
    path('home/', index, name = 'home'),
    path('add_status/', add_status, name = 'add_status'),
    path('about/', about, name = 'about'),
    path('book_list/', book_list, name = 'book_list'),
    path('book_data/<str:url>/', book_data, name='book_data'),
]

lab_10/models.py
from django.db import models

class Subscriber(models.Model):
    name = models.CharField(max_length = 40)
    email = models.EmailField()
    password = models.CharField(max_length = 20)

lab_11/models.py
from django.db import models

# Create your models here.

lab_6/models.py
from django.db import models

class Status(models.Model):
    my_status = models.TextField(max_length = 300)
    created_date = models.DateTimeField(auto_now_add = True)

lab_6/forms.py
from django import forms

class Status_Form(forms.Form):
    error_message = {
        'required': 'Please fill this field',
    }

    status_attrs = {
        'type': 'text',
        'class': 'form-control todo-form-textarea',
    }

    my_status = forms.CharField(
        required = True,
        widget = forms.Textarea(attrs = status_attrs),
        max_length = 300,
        label = '')

lab_10/views.py
from django.shortcuts import render
from .models import Subscriber
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

def index(request):
    return render(request, 'lab_10/registration.html')

def new(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        password = request.POST['password']

        new_subscriber = Subscriber.objects.create(
            name = name,
            email = email,
            password = password,
        )
        new_subscriber.save()

        return HttpResponse('')
    else:
        return HttpResponseRedirect('/registration/')
    
def email_checking(request):
    emailIsExist = False
    if 'email' in request.POST:
        count = Subscriber.objects.filter(email = request.POST['email']).count()
        if count > 0: emailIsExist = True
    return JsonResponse({"email_is_exist": emailIsExist}, content_type = 'application/json')

def subscriber_list(request):
    return render(request, 'lab_10/subscriber_list.html')

def subscriber_data(request):
    subscriber_object = Subscriber.objects.all().values('name', 'email')
    subscriber_list = list(subscriber_object)

    return JsonResponse(subscriber_list, safe = False)

# def password_confirmation(request):
#     def first(query):
#         try:
#             return query.all()[0]
#         except:
#             return None

#     if request.method == 'POST':
#         email = request.POST['email']
#         password = request.POST['password']
#         objects = first(Subscriber.objects.filter(email=email))
#         if password == objects.password:
#             Subscriber.objects.filter(email=email).delete()
#             return JsonResponse({"password_is_valid": True}, content_type = 'application/json')
#         else:
#             return JsonResponse({"password_is_valid": False}, content_type = 'application/json')

lab_11/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse 
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout as logout_user
import requests
import json

response = {}
def index(request):
    return render(request, 'lab_11/index.html')

def logout(request):
    logout_user(request)
    return HttpResponseRedirect('/book/')

def google_book(request, url='quilting'):
    book_object = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + url)
    
    book_json = book_object.json()
    book_data = []
    star_count = 0
    for data in book_json['items'] :
        favorited = request.session.get(data['id'], False)
        item = {}

        item['id'] = data['id']
        if favorited:
            item['favorited'] = True
            star_count += 1
        else:
            item['favorited'] = False
        
        try: item['cover'] = data['volumeInfo']['imageLinks']['smallThumbnail']
        except: item['cover'] = "none"

        try: item['title'] = data['volumeInfo']['title']
        except: item['title'] = "none"

        try: item['authors'] = ", ".join(data['volumeInfo']['authors'])
        except: item['authors'] = "none"

        try: item['year_published'] = data['volumeInfo']['publishedDate'][:4]
        except: item['year_published'] = "none"
            
        book_data.append(item)
    book_data[1] = star_count
    return JsonResponse({"data" : book_data})

@csrf_exempt
def favorite(request):
    book_data = json.loads(request.body.decode())
    try:
        id = book_data['id']
        favorited = book_data['favorited']
        request.session[id] = favorited
        return HttpResponse(status=204)
    except KeyError:
        return HttpResponse(status=400)

lab_6/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse 
import requests
import json

from .forms import Status_Form
from .models import Status

response = {}
def index(request):
    response['author'] = "Clouddian Fazalmuttaqin"
    status_list = Status.objects.all()
    response['status_list'] = status_list
    html = 'landing_page.html'
    response['status_form'] = Status_Form
    return render(request, html, response)

def add_status(request):
    status = Status_Form(request.POST or None)
    if request.method == 'POST' and status.is_valid():
        response['my_status'] = request.POST['my_status']
        new_status = Status(my_status = response['my_status'])
        new_status.save()
        return HttpResponseRedirect('/home/')
    else:
        return HttpResponseRedirect('/home/')

def about(request):
    return render(request, 'about.html')

def book_list(request):
    return render(request, 'book_list.html')

def book_data(request, url):
    book_object = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + url)
    
    book_json = book_object.json()
    book_data = [];
    for data in book_json['items'] :
        item = {}
        
        try:
            item['cover'] = data['volumeInfo']['imageLinks']['smallThumbnail']
        except:
            item['cover'] = "none"

        try:
            item['title'] = data['volumeInfo']['title']
        except:
            item['title'] = "none"

        try:
            item['authors'] = ", ".join(data['volumeInfo']['authors'])
        except:
            item['authors'] = "none"

        try:
            item['year_published'] = data['volumeInfo']['publishedDate'][:4]
        except:
            item['year_published'] = "none"
            
        book_data.append(item)
        
    return JsonResponse({"data" : book_data})

lab_10/templates/lab_10/layout/base.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>CLOUD PROFILE</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://code.jquery.com/qunit/qunit-2.4.1.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/lab_10.css' %}" rel="stylesheet">
  </head>

  <body onload="myFunction()" style="margin:0;">
    <div id="loader"></div>
    <div style="display:none;" id="myDiv" class="animate-bottom">
      <header>
        {% include 'lab_10/partials/header.html' %}
      </header>

      {% block content %}
      {% endblock %}

      <footer class="container py-5 text-center">
        {% block footer %}
        {% include 'lab_10/partials/footer.html' %}
        {% endblock %}
      </footer>
    </div>
    

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> -->
    <script src="{% static 'js/lab_10.js' %}"></script>
    <script>
      var myVar;

      function myFunction() {
          myVar = setTimeout(showPage, 1500);
      }

      function showPage() {
        document.getElementById("loader").style.display = "none";
        document.getElementById("myDiv").style.display = "block";
      }
    </script>
  </body>
</html>

lab_10/templates/lab_10/partials/footer.html
<!-- Fixed footer -->
<h1 class="display-5" id="footer">Believe more in millions dollar execution</h1>

lab_10/templates/lab_10/partials/header.html
<!-- Fixed header navbar -->
<nav class="sticky-top navbar navbar-expand-sm navbar-dark bg-dark" id="header">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample03">
        <div class = "mr-2"><a class="btn btn-primary" href="{% url 'registration' %}">Register</a></div>
        <a class="btn btn-primary" href="{% url 'subscriber_list' %}">Subscriber List</a>
        <ul class="navbar-nav ml-auto mr-2">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}" id="home">Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>

lab_10/templates/lab_10/registration.html
{% extends 'lab_10/layout/base.html' %}
{%load static%}

    {% block content %}
    <form class="form-signin text-center" id="form-registration">
        {% csrf_token %}
        <h1 class="h3 mb-3 font-weight-normal">Registration</h1>

        <label for="inputName" class="sr-only">Your name</label>
        <input type="text" id="inputName" class="form-control" placeholder="Your name" oninput="nameValidation()">
        <div id="invalid-name"></div>

        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" oninput="emailValidation()">
        <div id="invalid-email"></div>

        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" oninput="passwordValidation()">
        <div id="invalid-password"></div>
        <br>
        <button class="btn btn-lg btn-primary btn-block disabled" id="submit" type ="submit">Register</button>
    </form>

    {% endblock %}

lab_10/templates/lab_10/subscriber_list.html
{% extends 'lab_10/layout/base.html' %}
{%load static%}

    {% block content %}
    <nav class="m-4 pr-md-2">
      <nav class="container-fluid p-3">
          <h1 class="display-3">Subscriber List</h1>
      </nav>
    </nav>

    <nav class="m-4 pr-md-2" id="book-list">
      <nav class="container-fluid p-3">
        <table class="table table-bordered table-responsive-sm">
            <thead>
              <tr>
                <th scope="col">No</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Unsubscribe</th>
              </tr>
            </thead>
            <tbody id="table-body">
              <!-- content from Ajax -->
            </tbody>
          </table>


          <!-- <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Delete Confirmation</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="input-group mb-3">
                                <input type="password" class="form-control" id = "password-confirm" placeholder="Please input your password" aria-label="Recipient's username" aria-describedby="button-addon2">
                            </div>
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" id="delete" onclick = "confirmPassword()">Delete</button>
                        </div>
                    </div>
                </div>
            </div> -->
        </nav>
    </nav>

    {% endblock %}

lab_11/templates/lab_11/index.html
{% extends 'lab_11/layout/base.html' %}
{%load static%}

    {% block content %}
    <nav class="m-4 pr-md-2">
        <nav class="container-fluid p-3">
            <h1 class="display-3">JSON Google Book Viewer</h1>
            {% if user.is_authenticated %}
            <h1 class="display-4">Hi, {{ user.first_name }}</h1>
            {% else %}
            <h1 class="display-4">Hi, Please login first</h1>
            {% endif %}
        </nav>
    </nav>

    {% if user.is_authenticated %}
    <nav class="m-4 pr-md-2">
        <nav class="container-fluid p-3">
            <nav>
                <h1 class="display-5">★: <span id="favorite-count"></span> Favorite book</h1>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" id="text-search" placeholder="Search book..." aria-label="Recipient's username" aria-describedby="button-addon2">
                    <div class="input-group-append">
                    <button class="btn btn-outline-white" type="button" id="button-search" onclick='search()'>Search</button>
                    </div>
                </div>
            </nav>
        </nav>
    </nav>

    <nav class="m-4 pr-md-2" id="book-list">
        <nav class="container-fluid p-3">
            <table class="table table-bordered table-responsive-sm">
                <thead>
                <tr>
                    <th scope="col">Cover</th>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Year Published</th>
                    <th scope="col">Favourite</th>
                </tr>
                </thead>
                <tbody id="table-body">
                <!-- content from Ajax -->
                </tbody>
            </table>
        </nav>
    </nav>
    {% endif %}
    {% endblock %}

lab_11/templates/lab_11/layout/base.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>CLOUD PROFILE</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://code.jquery.com/qunit/qunit-2.4.1.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/lab_11.css' %}" rel="stylesheet">
  </head>

  <body onload="myFunction()" style="margin:0;">
    <div id="loader"></div>
    <div style="display:none;" id="myDiv" class="animate-bottom">
      <header>
        {% include 'lab_11/partials/header.html' %}
      </header>

      {% block content %}
      {% endblock %}

      <footer class="container py-5 text-center">
        {% block footer %}
        {% include 'lab_11/partials/footer.html' %}
        {% endblock %}
      </footer>
    </div>
    

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script src="{% static 'js/lab_11.js' %}"></script>
    <script>
      var myVar;

      function myFunction() {
          myVar = setTimeout(showPage, 1500);
      }

      function showPage() {
        document.getElementById("loader").style.display = "none";
        document.getElementById("myDiv").style.display = "block";
      }
    </script>
  </body>
</html>

lab_11/templates/lab_11/partials/footer.html
<!-- Fixed footer -->
<h1 class="display-5" id="footer">Believe more in millions dollar execution</h1>

lab_11/templates/lab_11/partials/header.html
<!-- Fixed header navbar -->
<nav class="sticky-top navbar navbar-expand-sm navbar-dark bg-dark" id="header">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample03">
        {% if user.is_authenticated %}
        <a class="text-white disable">{{ user.first_name }}</a>
        {% endif %}
        <ul class="navbar-nav ml-auto mr-2">
            {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'lab_11:logout' %}">Logout</a>
            {% else %}
            <a class="btn btn-primary" href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a>
            {% endif %}
        </ul>
    </div>
</nav>

lab_6/templates/about.html
{% extends 'lab_6/../layout/base.html' %}
{%load static%}

    {% block content %}
    <nav class="m-4 pr-md-2">
      <div class="container-fluid" id="my_bio">
        <div class="row">
          <div class="col-sm-3 p-0">
            <img src="{% static 'images/cloud.png' %}" class="featurette-image img-fluid mx-auto">
          </div>
          <div class="col-sm mb-0 pb-0 pl-3">
            <div class="row pl-3 pt-3 pt-md-5">
              <h4>“A dedicated student with proven analysis and problem-solving skills, highly interested in business and IT development”</h4>
            </div>
            <div class="row pt-md-3">
              <div class="col-sm ml-3 mt-4">
                <h4 class="sub2-header m-0">CONTACT</h4>
                <p class="contain m-0">+62 877 1177 6565</p>
                <p class="contain m-0">clouddian.fazalmuttaqin@ui.ac.id</p>
                <p class="contain m-0">Depok, West Java, Indonesia</p>     
              </div>
              <div class="col-sm ml-3 mt-4 pl-3">
                <h4 class="sub2-header m-0">EDUCATION</h4>
                <p class="contain m-0">Bachelor of Science, Majoring Information System</p>
                <p class="contain m-0">Universitas Indonesia</p>
                <p class="contain m-0">2017 - 2021 (EXPECTED)</p>    
              </div>
            </div>
            <div class="row mt-4 mt-md-5">
              <div class="ml-3 pl-3 mb-3">
                <h4 class="sub2-header m-0">SKILLS</h4>
                <p class="contain m-0">- Sufficient understanding in Python and Java.</p>
                <p class="contain m-0">- Well knowledge in Agile and the use of SCRUM Framework.</p>
                <p class="contain m-0">- Experienced in team management.</p>
                <p class="contain m-0">- Strong problem-solving and analysis skills.</p>
                <p class="contain m-0">- Product-Tools Used: Jira, Confluence, Trello, Marvel, Figma</p>
                <p class="contain m-0">- Dev-Tools Used : Git, Marvel, Intellij</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <nav class="m-4 pr-md-2">
      <div id="accordion">
        <h3 class="container-fluid">Experience</h3>
        <div>
          <div>
            <div class="row">
              <h5 class="m-0 pl-2 my-auto">Product Manager Internship</h5> 
            </div>
            <div class="row">
              <p class="contain m-0 p-2">During the internship period, I was involved in monitoring and enhancing Bizzy catalog product. My responsibilities include: (1) Conduct analysis for product enhancement; (2) Establish comprehensive documentation of product specs; (3) Monitor product and sprint backlog; (4) Define and break down clear product requirement to Tech Team and Product Design; (5) Conduct user testing with Product Design; (5) Maintain Bizzy active SKU with Content and Merchandise Team.</p>
            </div>
          </div>
          <div>
            <div class="row">
              <h5 class="m-0 pl-2 my-auto">Teaching Assistant of Discrete Mathematics 1</h5>  
            </div>
            <div class="row">
              <p class="contain m-0 p-2">My responsibility is to help the lecturer in assisting students whenever they need help, setting up and evaluating their assignments, and overseeing their exams.</p>
            </div>
          </div>
          <div>
            <div class="row">
              <h5 class="m-0 pl-2 my-auto">Delegate of SxC Future Leader Academy</h5>
            </div>
            <div class="row">
              <p class="contain m-0 p-2">Elected as a delegation in the biggest event organized by StudentsxCEOs. Presenting my idea in FinTech about digitizing SMEs, providing cashless transaction and giving accurate recommendation using Big Data.</p>
            </div>
          </div>
        </div>

        <h3 class="container-fluid">Organization/Committee</h3>
        <div>
          <div>
            <div class="row">
              <h5 class="m-0 pl-2 my-auto">Staff of Academics and Leadership</h5> 
            </div>
            <div class="row">
              <p class="contain m-0 p-2">Responsible for caring and helping some students in facing their academic issue, generate the spirit of leadership inside every computer science student, and give students support in preparing their post-graduate life.</p>
            </div>
          </div>
          <div>
            <div class="row">
              <h5 class="m-0 pl-2 my-auto">Staff of Business IT Case</h5>  
            </div>
            <div class="row">
              <p class="contain m-0 p-2">Compfest is one of the biggest IT events held by the students of the Computer Science UI with Business IT Case as one of the competition. My responsibilities include conduct partnership with several potential partners, establish all document partnership (MoU, ToR), and collaborate with other members in executing all the rundown.</p>
            </div>
          </div>
        </div>
        <h3 class="container-fluid">Achievement</h3>
        <div>
          <div>
            <div class="row">
              <h5 class="m-0 pl-2 my-auto">Top 10 Semifinalist of Information System Case Competition 2018</h5> 
            </div>
            <div class="row">
              <p class="contain m-0 p-2">ISCC is is an international level business case competition held by Binus International Association of Information Systems. In 2018, ISCC proposes "HealthTech" as its competition theme outline. Me and my team manage to become top 10 semifinalists out of 40+ teams submission, with 25% international teams like from Hongkong and Malaysia and 75% national teams from many prominent universities in Indonesia likes ITB, ITS, Binus, and President University.</p>
            </div>
          </div>
          <div>
            <div class="row">
              <h5 class="m-0 pl-2 my-auto">1st Runner Up of School of Indonesian Youth Entrepreneur (SHINE) Business Plan Competition</h5>  
            </div>
            <div class="row">
              <p class="contain m-0 p-2">SHINE is a series of events organized by the International Business Students Association from D3 FEB UNPAD to explore entrepreneurship potential, improve the skills and practice in making business plans, and create ideas that can compete in international markets of Asian Economic Community (AEC). Me and my team successfully managed to become top 3 finalists.

Thru the competition, we were challenged to invent an outstanding business idea that can solve Indonesia major problem. as a final result, we proposed job matchmaking platform based mobile application which connects talented students with reputable companies to resolved Indonesia human resource issues and successfully got 1nd runner-up position in the final round.</p>
            </div>
          </div>
          <div>
            <div class="row">
              <h5 class="m-0 pl-2 my-auto">1st Runner Up of HIMSISFO IS Case Solution (IS CASO)</h5>
            </div>
            <div class="row">
              <p class="contain m-0 p-2">EIS Case Solution is a national level business IT case competition held by Information Systems Student Association, Binus University.

In this competition, me and my team were challenged to present ripping solution that can solve Uber company problem containing brand improvement, marketing strategy, system transparency, and future recommendation to leveraging Uber business value. In our final result, we recommend Uber to establish rush hour maps, transparent payment and expand their business to India. The judges for the final round are an experts developer and lecturer. Finally, we finished the competition in 2nd place.</p>
            </div>
          </div>
        </div>
      </div>
    </nav>

    {% endblock %}

lab_6/templates/partials/footer.html
<!-- Fixed footer -->
<h1 class="display-5" id="footer">Believe more in millions dollar execution</h1>